import '../globals.css';
import { getPages } from '@/sanity/sanity-utils';
import Footer from '@/src/components/Footer'
import Header from '@/src/components/Header';

export const metadata = {
  title: 'Livra Space',
  description: 'Generated by Next + Sanity',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pages = await getPages();

  return (
    <html lang='en'>
      <body className='max-w-3xl mx-auto py-10'>
        <Header pages={pages} />
        <main className=''>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
