import '../globals.css';
import { getPages } from '@/sanity/sanity-utils';
import Footer from '@/src/components/Footer';
import Header from '@/src/components/Header';

interface Page {
  _id: string;
  slug: string;
  title: string;
}

export const metadata = {
  title: 'Livra Space',
  description: 'Generated by Next + Sanity',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pages: Page[] = (await getPages()) || [];

  return (
    <>
      <div className='min-h-screen flex flex-col'>
        <Header pages={pages} />
        <main className="flex-grow">{children}</main>
        <Footer />
      </div>
    </>
  );
}
